version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: super-payment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: super_payment
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - super-payment-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Super Payment API
  api:
    build: .
    container_name: super-payment-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: super_payment
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRY_HOURS: 24
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - super-payment-network

  # phpMyAdmin (optional, for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: super-payment-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - super-payment-network

volumes:
  mysql_data:

networks:
  super-payment-network:
    driver: bridge
